# Generated by Django 6.0.2 on 2026-02-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compositor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("biografia", models.TextField(blank=True, null=True)),
                ("epoca", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("requiem", "Réquiem"),
                            ("vals", "Vals"),
                            ("sinfonia", "Sinfonía"),
                            ("sonata", "Sonata"),
                            ("concierto", "Concierto"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ano_composicion",
                    models.IntegerField(help_text="Año en el que se compuso"),
                ),
                (
                    "duracion_minutos",
                    models.IntegerField(help_text="Duración estimada en minutos"),
                ),
                (
                    "num_instrumentos",
                    models.IntegerField(help_text="Número de instrumentos necesarios"),
                ),
                (
                    "partitura",
                    models.FileField(blank=True, null=True, upload_to="partituras/"),
                ),
                (
                    "popularidad",
                    models.IntegerField(
                        default=0, help_text="Número de consultas/descargas"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "compositor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obras",
                        to="catalogo.compositor",
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]