# Generated by Django 6.0.2 on 2026-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]